# Generated by Django 2.2.6 on 2019-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproduct',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='postproduct',
            name='translit_title',
            field=models.CharField(blank=True, max_length=210, verbose_name='Транслит'),
        ),
    ]
