# Generated by Django 2.2.6 on 2019-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0002_auto_20191118_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproduct',
            old_name='first_appearance_date',
            new_name='last_update_date',
        ),
        migrations.AddField(
            model_name='postproduct',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postproduct',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
